### PR TITLE
Optimization of GetInventory() calls

### PR DESCRIPTION
**Pull request by Kermel**

### CODE REVIEW

**Comment by jjskuld** [comment]
@Kermel Thanks for this change. It's been bugging me as well.  Unfortunately the build is not successful with your pull. Can you rebase your pull request so that it passes the build check?

**Comment by Kermel** [comment]
@jjskuld Hi jjskuld, Good that it does not work here, I just discovered that it is still buggy (even more than it was :) ). Currently it seems that I have a fix ready which I will be committing soon if everything goes well.
(Hope this time the commit will be correct)

**Comment by jjskuld** [comment]
@Kermel i think we may have figured out the problem with GetInventory() calls failing randomly. I believe it was just fixed in latest FeroxRev.

Not sure what happened with that missing submodule.  It may be that you made some local changes to FeroxRev and did not open a pull request to https://github.com/Necrobot-Private/PokemonGo.RocketAPI.

Note that the way we do inventory is totally not how it should work.  The true GetInventory() is passed a timestamp of when you last checked the inventory and it gives you diff's of what has changed since you last checked.  This is how the real client does things.

On the other hand, we always get a full inventory by passing timestamp = 0.  So I think your changes will not work because the API is expecting full inventory when calling GetInventory()

**Comment by Kermel** [comment]
Yes, thats exactly what I figured today and why I canceleld the pull request. Need to fix this as well (to work with the "diffs"). Then we will have proper client emulation (at least in this area) and potentially avoid being flagged :-).
I am working on it but I am also quite busy at work so it make take a few days (evenings) to completely rewrite this functionality

**Pull request closed without merging**
