### PR TITLE
Update to POGOProtos 2.2.0

### PR DESCRIPTION
**Pull request by Furtif**
# Please Note (you may remove this section before opening your PR):
We receive lots of pull requests, please help us be able to review them by following the below guidelines:

1. If you are adding configuration settings, please be sure to document their usage in your description so they can be added to the wiki.
2. Make sure your code is clean and well-formed. Use comments if necessary to explain why you did something.
3. Make sure your changes are only for a specific purpose. Do not mix several changes into one pull request.
4. If the code is based off another individuals work, be sure to credit them appropriately.

### CODE REVIEW

**Comment by jjskuld** [comment]
By the way, we are no longer using our own pogoprotos but rather pogoprotos from nuget (AeonLucid netstandard1)

**Comment by Kermel** [comment]
Is the nuget always up-to-date? I remember that in summer there also was some POGO protos nuget, but it was completely outdated.
(Compiling our own C# sources from the most current POGO Protos would be the safest way)

**Comment by jjskuld** [comment]
@Kermel Yes, actually the Nuget is now always up-to-date since we are using the official AeonLucid pogoprotos and he is actively keeping nuget up-to-date.

**Comment by Furtif** [comment]
yes nuget $(SolutionDir)\packages\POGOProtos.NetStandard1.2.2.0\lib\net45\POGOProtos.NetStandard1.dll

**Comment by jjskuld** [comment]
I'm going to close this one out for now.  I've already updated POGOProtos in 0.47 branch.  As with the previous API changes, the 0.47 is not working yet.  Just getting things ready.

**Comment by jjskuld** [comment]
@Furtif One more suggestion for how to better collaborate on open source software. When you are creating pull requests, please make sure not to change the submodule to point to your own fork:
```
 [submodule "FeroxRev"]
  	path = FeroxRev		  	path = FeroxRev
+	url = https://github.com/Furtif/FeroxRev.git
+	branch = master
```

The better way is to open a pull request in NecroBot-Private's FeroxRev and then only after that pull has been accepted you can reference the new version.

We cannot accept the pull as-is because it is going to be making builds out of your version of the code and not ours.

**Comment by Furtif** [comment]
@jjskuld  I know it well but I make the proposals via github and I forget each time to change the modules ... sorry.

**Comment by jjskuld** [comment]
@Furtif No worries, by the way thank you for continuing to support us and contributing back to us!

**Pull request closed without merging**
