### PR TITLE
More Updates read descript

### PR DESCRIPTION
**Pull request by Furtif**
# Merge PR submodules opened

- Auto Walk & AccountLon/Lat fixes
- AutoWalkAI Fixes
- removed unused lines
- fixed order of multi accounts
- Bug fixes & updates

### @TheWizard1328

- 1) Added logger lines for transfers(Weak, Duplicate, Slashed)
- 2) Sorft Order of accoutns when displayed.
- 3) better selecting of accounts(Will auto pick account with lowest Lvl & XP)
- 4) Added ActiveAccount to enable/Disable accounts even at runtime.(Still a Few bugs)
- 5) Added Accounts tab in settings for use with ActiveAccount.
- 6) Added all "MultipleBotConfig" vars into Settings "Advanced Settings" tab.
- 7) Tweeked AutoWalkAI.
- 8) Disabled "Switch bot account, Activated by:" Pushbullet notification.(Trying to move it to "Account Changed to:" PB section)

### Allows users to use another server hash in rocketbot
ex:

```
"APIConfig": {
    "UsePogoDevAPI": false,
    "AuthAPIKey": "KEY_SERVER_HERE",
    "UseCustomApi": true,
    "DiplayHashServerLog": false,
    "UrlHashServices": "URL_SERVER_HERE",
    "EndPoint": "END_POINT_HERE"
  }
 ```

### CODE REVIEW

**Comment by CDAGaming** [comment]
@Lord-Haji Follow The instructions. Since you merged one you have to merge it all or the entire build will break (The Submodules all work towards this PR)

**Comment by myogui** [comment]
is the branch concerned by the PR is in origin? I can't click on it or find it in the branchs. thx

**Comment by CDAGaming** [comment]
It's in @Furtif 's Fork of Necrobot and in My fork, in a branch titled 'rocketbot_updates'
@myogui

**Comment by myogui** [comment]
Is this config enough to enable snipe walk? I'm using the code from Furtif:rocketbot_updates .doesn't seem to work for me:

```

  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": true,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 10,
    "MinLevelForAutoSnipe": 0,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 10
  },
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 100.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false,
    "AllowTransferWhileWalking": false
  },
  "DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://www.mypogosnipers.com/socket.io/?EIO=3&transport=websocket"
  },
```

**Comment by Furtif** [comment]
missed HumanWalkSnipeFilter @myogui

**Comment by myogui** [comment]
Here is some of it:

```
  "HumanWalkSnipeFilters": {
    "Magikarp": {
      "MaxDistance": 300.0,
      "Priority": 10,
      "MaxWalkTimes": 200.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 100.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 10,
      "AllowTransferWhileWalking": false
    },
    "Eevee": {
      "MaxDistance": 1000.0,
      "Priority": 10,
      "MaxWalkTimes": 600.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 100.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 10,
      "AllowTransferWhileWalking": false
    },
    "Electabuzz": {
      "MaxDistance": 3000.0,
      "Priority": 2,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 100.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 10,
      "AllowTransferWhileWalking": false
    },
    "Dragonite": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 100.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 10,
      "AllowTransferWhileWalking": false
    },
    "Dragonair": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 100.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 10,
      "AllowTransferWhileWalking": false
    },
```

**Comment by myogui** [comment]
@Furtif when you have a minute please have a look ^ 

Thanks

**Comment by Furtif** [comment]
?! Yes

**Comment by myogui** [comment]
Are my settings OK for sniping?

**Comment by Furtif** [comment]
yes

**Pull request merged**
