### PR TITLE
Change Api calls methods

### PR DESCRIPTION
**Pull request by Furtif**
* Change Api calls methodes https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/fb2f5953a46e3901c9cb621206ca662681ff6ab0
* Set default item quantity of items https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/4edcc6269e22a6a17f4ab5217752f9813226f394
* Fixes assistant config for frist start https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/f812a302c7e061d5ce8df41a581125fbb688d6d9
* Add shiny pack https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/db9f381ce633c292f79030232cfa16a3249237db https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/1fd86fb87332d8870b0964831a2a7561ecf654f0
* AutoWalkAI addon & LoadPokeStopsTimer modification https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/22d90bdc989cf6c6901476f0a2734b15c2e01d7d
* Random request ID generation https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/f15867fbe33a38f5b855041075d94b1c07477306 https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/1fd86fb87332d8870b0964831a2a7561ecf654f0
* Add new platform request: JOIN_EVENT https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/330bf7119a6e794c63b1a2c9ceeaae53349ba882

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Your last commit is bugged too, bag says full when its not

**Comment by Furtif** [comment]
not is no buggued, It's just that this did not count the items evo but they exist well the problem and in it:
```
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 80.0,
    "RandomizeRecycle": true,
    "RandomRecycleValue": 3,
    "TotalAmountOfPokeballsToKeep": 100,
    "TotalAmountOfPotionsToKeep": 75,
    "TotalAmountOfRevivesToKeep": 75,
    "TotalAmountOfBerriesToKeep": 45,
    "TotalAmountOfEvolutionToKeep": 25,
    "UseRecyclePercentsInsteadOfTotals": false,
    "PercentOfInventoryPokeballsToKeep": 35,
    "PercentOfInventoryPotionsToKeep": 35,
    "PercentOfInventoryRevivesToKeep": 20,
    "PercentOfInventoryBerriesToKeep": 10,
    "PercentOfInventoryEvolutionToKeep": 10
  },
```
If you depase 350 of the error but this is just a calculation bug nothing much.

**Comment by Furtif** [comment]
You may want to put good default values in the file https://github.com/Necrobot-Private/NecroBot/blob/master/PoGo.NecroBot.Logic/Model/Settings/ItemRecycleConfig.cs#L62 among other values even without the addition of Items evo the default numbers are bad, but since this item was not counted before and the configs users were accustomed to configure only the base ite there was not so much problem I will change it .....

**Comment by Furtif** [comment]
I already put this with believable values. https://github.com/Necrobot-Private/NecroBot/pull/1950/commits/4edcc6269e22a6a17f4ab5217752f9813226f394

**Comment by Lord-Haji** [comment]
@Furtif Update RocketAPI

**Comment by Lord-Haji** [comment]
@Furtif Update PokemonGO-Assets

**Comment by Lord-Haji** [comment]
@Furtif Update submodules

**Pull request merged**
