### PR TITLE
Refactoring - Move listeners from CLI to logic.

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
Refactoring - move some of the listener logic from CLI to Logic since it is used by multiple projects (i.e. RocketBot) and shouldn't be duplicated.

### CODE REVIEW

**Comment by Furtif** [comment]
this clean speed label in rb!

**Comment by jjskuld** [comment]
Ok I will add it.

**Comment by Lord-Haji** [comment]
@jjskuld what does Furtif mean ?

**Comment by jjskuld** [comment]
Actually since MainForm doesn't exist in NecroBot, we'll have to add a delegate here.
I'll fix it up.

@Lord-Haji We're consolidating some shared classes that were duplicated but RocketBot has some additional modifications that we don't have.

**Pull request merged**
