### PR TITLE
VS2017-build

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by CDAGaming** [comment]
Added to my PR @Lord-Haji , may make it auto detect arcitecture and build an appropriate copy

**Comment by CDAGaming** [comment]
Your Build.bat would only Work for YOUR visual studio @Lord-Haji , for now this would be used for VS2017 Community, which most would use:

Code: 
echo off
echo Building in %processor_architecture%

if "%processor_architecture%"=="AMD64" (
nuget.exe restore "NecroBot-Private for Pokemon GO.sln"
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "NecroBot-Private for Pokemon GO.sln" /property:Configuration=Release /property:Platform=x64
) ELSE (
nuget.exe restore "NecroBot-Private for Pokemon GO.sln"
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "NecroBot-Private for Pokemon GO.sln" /property:Configuration=Release /property:Platform=x86
)

**Comment by hardknoxni69a** [comment]
i wouldnt do this pr as the devs use visual studio to build and not a bat file. this file is for the basic user who wants to compile using only msbuild they shouldnt have to have VS 2017 installed

**Comment by CDAGaming** [comment]
@hardknoxni69a From Recent Changes, VS2017 is now required to build Source...

**Comment by jjskuld** [comment]
It requires MSBuild 15 or VS2017 (support for C# 7.0).  Sounds like it's a complicated issue since MSBuild.exe can be in different locations.

See https://github.com/cake-build/cake/issues/1369

**Comment by CDAGaming** [comment]
Jjskuld, I can make a batch or edit the one I mentioned to detect if a Version exists and use correct msbuild

**Comment by hardknoxni69a** [comment]
I believe editing the bat so it checks for msbuild in stock location or vs location and will use 14 or 15 would be best but right now it's set to only use VS 2017 Msbuild which few will have

**Comment by CDAGaming** [comment]
I'll be available to do that today :)

**Comment by CDAGaming** [comment]
Will Only have it support VS2015 or VS2017 editions

**Comment by hardknoxni69a** [comment]
while your at it you misewell have it do 2013 and any others that will successfully build it. it should just find the location of msbuild no matter the location including self installed or vs installed

**Comment by CDAGaming** [comment]
@hardknoxni69a Will do, So far VS2015 & VS2017 should have confirmed build Success, and i don't think VS versions lower than 2010 will work, so i'd have one other to text

Batch Preview:

if exists "VS2015CommunityDirHere" goto VS2015_Community
if exists "VS2017CommunityDirHere" goto VS2017_Community

:VS2017_Community
if "%processor_architecture%"=="AMD64" (
nuget.exe restore "NecroBot-Private for Pokemon GO.sln"
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "NecroBot-Private for Pokemon GO.sln" /property:Configuration=Release /property:Platform=x64
) ELSE (
nuget.exe restore "NecroBot-Private for Pokemon GO.sln"
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "NecroBot-Private for Pokemon GO.sln" /property:Configuration=Release /property:Platform=x86
)

:VS2015_Community
// VS 2015 Code Here,relating to VS2017 Build Code

**Comment by CDAGaming** [comment]
Added into https://github.com/Necrobot-Private/NecroBot/pull/1513

**Pull request closed without merging**
