### PR TITLE
Autosnipe min lvl

### PR DESCRIPTION
**Pull request by ziomber**
Added min lvl for autosnipe (fixed and operator to IV like it was)
Little change in gym to bypass UsePokemonToAttackOnlyByCp setting when is only one defender in gym

### CODE REVIEW

**Comment by samuraitruong** [comment]
this is overlap with my current PR :) I already make changes for AutoSnipeMinLevel in my PR. could you revert that and only keep change for GYM

**Comment by ziomber** [comment]
merged
i've add one try..catch in filterutil becouse i've got some null point there

**Comment by ziomber** [comment]
it should be ready now...

**Comment by samuraitruong** [comment]
merged. thanks

**Pull request merged**
