### PR TITLE
Gym attack module tunning

### PR DESCRIPTION
**Pull request by ziomber**
Timings are improved as much as possible, no any bad attack exceptions.
If start gym attack exception is throwed i try to refresh gym data before enter again
also, if no usable gym can be found i'm trying refresh all gym list
Added config option to stop attack gyms when you have reached CollectCoinAfterDeployed.
GYM Observations #551 :
1 and 3 are done, 
2 is risky, may produce big loop on one gym untill heal/revive potions will not finish, 
4 is possible, but as for now i don't know how to start it
5 it will be my next step...

### CODE REVIEW

**Comment by samuraitruong** [comment]
it has merge conflict, can you pull master and resolve it.

**Comment by samuraitruong** [comment]
Also there is abug that after attack we not put pokemon into the gym, or gym level 0 be ignored.

**Comment by sammy150681** [comment]
#our attack timed out..  noone pokemon us defeated

**Comment by ziomber** [comment]
i'll merge ofc :)
this bug was solved on the begining

**Comment by ziomber** [comment]
@sammy150681 most probable pokemon set was to low to take gym, but now, attacks are much faster and there is no problem with special attacks so damage is much higher and chance to win also

**Comment by samuraitruong** [comment]
@ziomber Any new commit? I going to make release before go to bed

**Comment by ziomber** [comment]
One fast last opimization

**Comment by ziomber** [comment]
@samuraitruong going to sleep? is middle of the day :)

**Comment by samuraitruong** [comment]
we are international team. I am UTC+11 AM  now.

**Comment by RudeCP** [comment]
"2 is risky, may produce big loop on one gym untill heal/revive potions will not finish"

I think 2 is real world.  People keep attacking Gym's until they win or run out of potions.  I think it looks weird if the bot attacks and moves on...

**Comment by adrianmateii** [comment]
there is no dodge right? cause if we will have pokemons dodging special attacks from defenders then the fight can be won even with low lvl pokemons

**Pull request merged**
