### PR TITLE
3 news features

### PR DESCRIPTION
**Pull request by samuraitruong**
hi Guys,

Since all the code was work in progress for a while so these change are include lot of code change but basically it has 3 feature

- Allow multiple bot config & auto switch to 
- Add ability to use excel config file (It will handle config.json file automatically) run with command necrobot2.exe -use_excel_config . I added bat file to run this. 
- Auto snipe with filter setting (work with mypogosnipers)

Few people has use those feature with the build I shared on room chat. I think it good enough.

One again, sorry to PR a massive code changes

### CODE REVIEW

**Comment by msx752** [comment]
@samuraitruong  default config.json getting error
as you see the line number
error1

**Comment by jjskuld** [comment]
@samuraitruong I see a bunch of FPM code changes in there.  I thought FPM was down, just curious why the changes?

**Comment by jjskuld** [comment]
Just a quick heads to all developers regarding new config version schema.  Whenever a change to any of the settings is made (anything that affects the config.json), you need to do several things:

1. Increase the `UpdateConfig.CURRENT_SCHEMA_VERSION` in `UpdateConfig.cs`.
2. Add migration steps to `GlobalConfig.MigrateSettings()`.

Just as an example, if you changed:
```
        [DefaultValue(1250)]
        [Range(0, 9999)]
        [JsonProperty(Required = Required.DisallowNull, DefaultValueHandling = DefaultValueHandling.Populate, Order = 1)]
        public int SnipeIV {get; set;}
```

to
```
        [DefaultValue(76)]
        [Range(0, 100)]
        [JsonProperty(Required = Required.DisallowNull, DefaultValueHandling = DefaultValueHandling.Populate, Order = 1)]
        public int SnipeIV {get; set;}
```

This would break validation for anyone that had the previous default of 1250.  So you would want to edit the JSON in `GlobalConfig.MigrateSettings()` so that any out of range values get set to valid values.

This would transparently fix errors like @msx752 was seeing above.

**Comment by jjskuld** [comment]
I'm also getting a `Cannot write a null value for property 'BotSwitchPokemonFilters'. Property requires a non-null value.` on startup with old configuration.  I'll see if i can fix it.

**Comment by samuraitruong** [comment]
Thanks guys, I look into those comment later tonight. Please keep update if you already fix them . @msx752   next time when you run, you still has to run with parameter to read xls config. program still loading json and display validation message there but it actually use excel config . I will change the logic not load json and display validation message if run with excel config command line

**Comment by samuraitruong** [comment]
FPM Code was my code use to test few feature long ago. it is useless now but in the future we if FPM come back. then we need it. I think we can keep in in source.

**Comment by jjskuld** [comment]
I ran into this bug while running overnight:
```
[04:47:40] (ERROR) Error loading data from Pokecrew
[04:47:41] (ERROR) Error loading data from PokeWatcher
[04:47:46] (SNIPER) (HUMAN WALK) Found 54 pokemon matched with you filters. Human walking sniper won't catch em all. but try to maximun catch if possible.
[04:47:46] (INFO)      Source      |  Name               |    Distance    |   Expires        |  Travel times   | Catchable
[04:47:46] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[04:47:46] (ERROR) Error: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: totalWidth
   at System.String.PadHelper(Int32 totalWidth, Char paddingChar, Boolean isRightPadded)
   at System.String.PadLeft(Int32 totalWidth, Char paddingChar)
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<PostProcessDataFetched>d__22.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 497
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<FetchData>d__19.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<GetNextSnipeablePokemon>d__18.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<Execute>d__13.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\skuld\Downloads\NecroBot-Private\PoGo.NecroBot.Logic\State\StateMachine.cs:line 91
```

**Pull request merged**
