### PR TITLE
Partial gyms fixes

### PR DESCRIPTION
**Pull request by Furtif**
*  https://github.com/Necrobot-Private/POGOProtos/pull/49  (Update POGOProtos 2.11.0 -beta - Platform Actions)
* https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/138 (update rocketapi try to fix forts reponses (gyms) )
* RocketBot release v2.11.0.1

### CODE REVIEW

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/139

**Comment by Lord-Haji** [comment]
Update RocketAPI again

**Comment by Furtif** [comment]
ready

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/140

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/PokemonGO-Assets/pull/16

**Comment by Furtif** [comment]
sans titre

**Pull request merged**
