### PR TITLE
Change console colors  for readability/contrast improvement.  Text co…

### PR DESCRIPTION
**Pull request by morbosc**
…lors change in CLI as well, but background there remains black (still relative improvement).  Unsure where to change it, but will keep looking and submit a followup if this is accepted.

Colors based off "Solarized" readability scheme.

### CODE REVIEW

**Comment by morbosc** [comment]
solarized

Here's what the console looks like in the GUI.  At the moment, CLI is still a black background. Obviously, up to you guys.

**Comment by Lord-Haji** [comment]
that background is having visibility issues ig

**Comment by morbosc** [comment]
Never had any problems with it in consoles and editors.  It's based off this:  http://ethanschoonover.com/solarized

No problem, anyway.  Just worked on it today, and can compile for personal use either way.  The current coloring gets a big strained after a day of watching consoles.  :-)

**Comment by Lord-Haji** [comment]
Make the background a bit darker and font colors a bit lighter ?

**Comment by morbosc** [comment]
I can take a look at it.  There was something in the console documentation that suggested C# shifts the colors off what's expected with the color coding I used.

**Comment by Lord-Haji** [comment]
Yep @morbosc

**Pull request merged**
