### PR TITLE
Updates Killswitch and Links (Replaces #1720)

### PR DESCRIPTION
**Pull request by CDAGaming**
Signed-off-by: CDAGaming <cstack2011@yahoo.com>

Replaces #1720

### CODE REVIEW

**Comment by jjskuld** [comment]
@CDAGaming Without good reason you shouldn't include another pull request in your own since it just makes your own pull harder to evaluate for changes.  So I've accepted #1720 first and then resolving the conflicts.

**Comment by CDAGaming** [comment]
Ok, as I only said it replaces it bc it covers a lot more areas than #1720

**Comment by jjskuld** [comment]
@CDAGaming Now after merging #1720 I can better see what your changes were that werre different from #1720.  After merging #1720 the only conflict I had to resolve with your pull with regards to the images is the change from 145.png to 0.png (and some minor whitespace changes).  Not sure if that image really matters, but I opted to restore the original image.

**Comment by jjskuld** [comment]
@CDAGaming Yup, your changes look good. Just waiting for the build to finish.

**Comment by CDAGaming** [comment]
Also Map Pokemon Marker was set to 0, to represent a proper placeholder, rather than a random pokemon. There is also extra indent in the other file too

**Comment by CDAGaming** [comment]
Nevermind on Extra Indent, looked extra from first glance from phone

**Comment by jjskuld** [comment]
One other thing to note. Rawgit is a CDN, so it will most likely cache the responses.  I suspect that if we make a change to the github file, Rawgit may end up serving up the old file for some time until the cache expires.  For that reason, it may be safer to change the version check, download, and killswitch urls back to github instead of Rawgit.

**Comment by CDAGaming** [comment]
Well, seemingly, I did test this, and it did seem to work out. It can go back to GitHub for now and I'll test it again on update to v173 and see if it works the same

**Comment by CDAGaming** [comment]
Or another option, as for me it seemed to work, we can use rawgit and if it doesn't work on v173 update or in the future we can easily swap back to github

**Comment by jjskuld** [comment]
Ok let's try it for now.

**Pull request merged**
