### PR TITLE
SuperBuild - Optimizations + More (Necrobot) - WIP

### PR DESCRIPTION
**Pull request by CDAGaming**
## Features
- All Dependencies Updated to Latest (No Issues @jjskuld, according to several tests)
- Many Typos have been Fixed
- Many Optimizations/Simplified Code-Behind for a Faster Experience
- Support for iOS Devices Up to 10.3
- Support for API 0.59.1 & 0.59.2 (Already in Official)
- License is now Properly an Embedded Resource so it is not visible
- Adds More Extended PokeEase Integration
- Fixes GUI Settings Descriptions (Empty or with typos, WIP)

## Known Bugs
- Sometimes, Going on the Hub/Browser Tab, the DotNetBrowser would take up the full screen
Workaround: Resize the screen a little bit for it to correct itself
- Sometimes, an error like the one below may appear when using 0.59 API (In Progress):
`[21:20:03] (ERROR) Hashing Servers errors, throttling calls. SESSION INVALIDATED EXCEPTION
[21:20:04] (ERROR) Resetting position before relogging in.`

## Requirements
- If you are Testing/Building this Source, Please don't forget to Get the other Pull Requests for the Submodules (FeroxRev)

## Downloads
Build 0401 - Coming in One Hour!
Build 0330 - [Click Here](https://mega.nz/#!3MhETZrK!m_H0g9QD7X9HgTxfJtLHR049kJfSELaZGTIr95nn88Q)

## Related PRs
[FeroxRev - Merged into Official](https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/98)

### CODE REVIEW

**Comment by jjskuld** [comment]
I'm doing a cherry-pick of the changes in this pull.  There are a couple of issues why this cannot be accepted as is:

1) Some recent commits were reverted (for example the ..\packages in the .csproj got introduced again).
2) Most of the method/property names that were lowercased were changed to uppercase. This is OK in most cases, EXCEPT when the class is used for json serialization (i.e. YoursWalk, GoogleWalk).  In this case the properties and names must match the JSON.  So these changes will cause runtime errors, despite compiling OK.
3) Out parameters syntax change is a breaking change for VS2015. So I'm reverting those changes.

**Comment by jjskuld** [comment]
Stay tuned.. will commit shortly

**Comment by CDAGaming** [comment]
Just Did one last optimization, so You are free to merge @jjskuld

**Comment by jjskuld** [comment]
Closed in favor of pull #1415.

**Pull request closed without merging**
