### PR TITLE
Delegate options

### PR DESCRIPTION
**Pull request by Furtif**
# Please Note (you may remove this section before opening your PR):
We receive lots of pull requests, please help us be able to review them by following the below guidelines:

1. If you are adding configuration settings, please be sure to document their usage in your description so they can be added to the wiki.
2. Make sure your code is clean and well-formed. Use comments if necessary to explain why you did something.
3. Make sure your changes are only for a specific purpose. Do not mix several changes into one pull request.
4. If the code is based off another individuals work, be sure to credit them appropriately.

### CODE REVIEW

**Comment by samuraitruong** [comment]
hey @Furtif ,

I am doing wpf gui as well, can you explain me what this the route use for? Since i may include it in my WPF UI

**Comment by Furtif** [comment]
@samuraitruong  Hello, I have its car every time I have conflicts in System.windows.forms (not xaml) and I want to carry a GUI interface on macOS X with visualStudio Preview, cella does nothing in current program and sa saves me to edit File has every pull, and if you wanted to use you could also have no problem.

**Comment by Furtif** [comment]
Xaml is not compatible in to VisualStudio Preview for macOs x (VisualStudio 2017) :-S

**Comment by Furtif** [comment]
@samuraitruong 
capture d ecran 2017-01-22 a 15 59 48
capture d ecran 2017-01-22 a 15 59 08
capture d ecran 2017-01-22 a 15 59 00
capture d ecran 2017-01-22 a 15 57 34

**Pull request closed without merging**
