### PR TITLE
Updates to rocket api to fix access token expiry bug.

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
Clean up access token handling to try to fix access token expiring too frequently.

Note: This needs more extensive testing, so please do not merge yet.

### CODE REVIEW

**Comment by jjskuld** [comment]
This is a fix for bug #770

**Comment by bulubebek** [comment]
I will give a test and lets see does it work as expected or not. Thank you for this PR. 👍

**Comment by gabrielb11** [comment]
what we need to do to solve this isssue?

**Comment by jjskuld** [comment]
Building a new release now which will solve this.

**Pull request merged**
