### PR TITLE
Updated Rocket API to add new cipher.

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
Updated Rocket API to add new cipher. Credits to Xelwon of Pokemaster Bot

### CODE REVIEW

**Comment by Lord-Haji** [comment]
@jjskuld One more update
Necrobot-Private/PokemonGO.RocketAPI@111be5f

**Comment by CDAGaming** [comment]
On a technicality, Crypto.cs is still relatively being used, as you can see the file and some contents still exist

**Comment by jjskuld** [comment]
@CDAGaming @Lord-Haji Good points, we'll clean that up.

**Comment by jjskuld** [comment]
Looks like Crypto is actually no longer used.  I'm going to remove some of the other old encryption as well.

**Comment by CDAGaming** [comment]
Ok Nice @jjskuld , preparing a new PR also for something else at this time, included in a Beta Release

**Pull request merged**
