### PR TITLE
Layout and Indent Fixes for PlayerInfo

### PR DESCRIPTION
**Pull request by CDAGaming**
Signed-off-by: CDAGaming <cstack2011@yahoo.com>

### CODE REVIEW

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/NecroBot/pull/1767

**Comment by CDAGaming** [comment]
#1768 References #1767 also, as it's his pr plus a sync with master plus some bug fixes

**Comment by Furtif** [comment]
https://github.com/CDAGaming/NecroBot/compare/master...Furtif:features/ManualPokeCoinCollection missing functions or properties

**Comment by CDAGaming** [comment]
@Furtif His feature was not working properly, so it won't be in this PR. You can use #1768 for reference to this PR with #1757 And #1767

**Comment by Furtif** [comment]
sans titre

If you save your build error see the comparisons

**Comment by Furtif** [comment]
integred #1767

**Pull request merged**
