### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by Furtif**
* Update submodules
* Try to show raids() RocketBot and WPF Gui
* Code Clean up @TheWizard1328 
* Add tarkbar zoom maim map (rocketbot)
* Fixed Catch Pokemon IV rounding  @TheWizard1328
* Add slashed propertie RocketBot and WPF Gui
* Translation Additons  @TheWizard1328
* Fixxed Evolve to pokemon  @TheWizard1328
* Update Dependencies

### CODE REVIEW

**Comment by Lord-Haji** [comment]
These images should go in assets repo and @TheWizard1328 where is the display for WIN GUI?

**Comment by TheWizard1328** [comment]
@Lord-Haji Not sure what you're asking???

**Comment by Furtif** [comment]
sans titre

**Comment by Furtif** [comment]
Maybe say so https://github.com/TheUnnamedOrganisation/RocketBot/commit/2a1dd890d109427b380c918af7e069c93d74d5a0

**Comment by Furtif** [comment]
sans titre

**Comment by Lord-Haji** [comment]
@TheWizard1328 the Raid display for the WIN GUI Map?

**Comment by Furtif** [comment]
is not ok almost @Lord-Haji

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/PokemonGO-Assets/pull/18/commits/c1ea8d99e5bc805180133a5c9be15d29c6895b61

**Comment by Lord-Haji** [comment]
@Furtif Update submodules and delete local assets

**Comment by Lord-Haji** [comment]
oops misclick

**Comment by Furtif** [comment]
sans titre

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/PokemonGO-Assets/pull/19

**Comment by Furtif** [comment]
sans titre
(bad image, good is affter merge Necrobot-Private/PokemonGO-Assets#19)

**Comment by Furtif** [comment]
sans titre

**Comment by zspam1** [comment]
Before you release the "Add slashed propertie", can you please test it? By my observation, all the pokemon's isBad == false returned by the Bossland API, even though it's slashed when login by phone.

**Comment by Furtif** [comment]
@zspam1 "Add slashed propertie" works fine 👍

**Comment by Furtif** [comment]
sans titre

**Comment by Lord-Haji** [comment]
The proper slash image isn't possible
So I think we'll need a slashed version of every Pokemon

**Pull request merged**
