### PR TITLE
KillSwitchOverride DialogBox

### PR DESCRIPTION
**Pull request by Furtif**
## DialogBox 	KillSwitchOverride 

sans titre

### CODE REVIEW

**Comment by jjskuld** [comment]
Thanks will test this shortly.

**Comment by jjskuld** [comment]
This is a fix for #1221.

**Comment by Furtif** [comment]
@jjskuld this:
//================================================================//

too long for dialog!!!

this

//============================================//

ok view this

https://github.com/Necrobot-Private/NecroBot/pull/1219/commits/7925558f02677541d64588a90d2e67563fdda8d2

**Comment by Furtif** [comment]
look this !! too long 

sans titre

**Comment by Furtif** [comment]
i m changed this is ok now

**Pull request merged**
