### PR TITLE
Adds Final FancyBuild Images & Cleans up Old Translations

### PR DESCRIPTION
**Pull request by CDAGaming**
## Description

This PR finishes Changes on FancyBuild, Adding the Final 3 Images to Tabs, and cleaning up unutilized Translations

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Pokemon count display? It's useful we should have it

**Comment by CDAGaming** [comment]
The Polls voted against any words on tabs though Haji, and I'm traveling tomorrow so idk if I'll have time to do that or put it somewhere else but I'll see

**Comment by Lord-Haji** [comment]
Ok

**Comment by jjskuld** [comment]
Let's go for it.. we can always improve again later.

**Pull request merged**
