### PR TITLE
Lure catch and end of trip for human snipe

### PR DESCRIPTION
**Pull request by samuraitruong**
-Enable catch lure pokestop at end of human snipe
-Refactor usenearbypoketops
-merge gym logic, gym now is a fort just like pokestop
-GPX path now will return to original location after snipe, will catch & fort pokestop on the way back. (need more test)

### CODE REVIEW

**Comment by iwean** [comment]
@samuraitruong 
So how to test it? The gym?

**Comment by samuraitruong** [comment]
I comment my gym . Will include in next pull request when combine it with refactore

**Comment by samuraitruong** [comment]
For gym testing

 "GymConfig": {

    "Enable": true,

    "MaxDistance": 250.0, that will be distance to look for gym. overwrite nearest pokestop if any gym closer than this distance.

    "DefaultTeam": "Yellow",

    "MaxCPToDeploy": 1000,

    "MaxLevelToDeploy": 16,

    "VisitTimeout": 60, //only visit a gym after 60 minutes


    "UseRandomPokemon": true, 

    "NumberOfTopPokemonToBeExcluded": 10
  },

**Comment by samuraitruong** [comment]
just found an issue, please hold on merge

**Pull request merged**
