### PR TITLE
Update bym battle module

### PR DESCRIPTION
**Pull request by ziomber**
## Short Description:
Fully fixed gym battle module. 
I've leaved lock on using attack mode for more test before public release.
I've tested on free api, don't have key for premium api so didn't tested...

### CODE REVIEW

**Comment by samuraitruong** [comment]
The gym attack isn't finish, I will have a look and merge this with my code base later.
thanks

**Comment by ziomber** [comment]
Check now :)

**Comment by ziomber** [comment]
it fixes Level 0 Gym ignored #529

**Comment by ziomber** [comment]
I have a question. I can't find any of api documentation. Is any function in api that i can use to swap pokemnos during battle? It will be best if i can select and use only good attackers not by cp but by type...

**Comment by ziomber** [comment]
I've done some optimizations ([Optimization] Skip walking to gyms that are full and/or owned by another team #512) but applied to current situation.
So, bot will don't go to gym where own pokemon is inside and bot will don't go to gym defended by other color and gym lvl is too high

**Comment by ziomber** [comment]
shit. I can't understand this forks, pulls,...
I love my old SVN... I just want to have fresh version...

**Pull request closed without merging**
