### PR TITLE
Bug fix/local sniping

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
Sniping is back!  This pull implements short range sniping (auto sniping works as well as manual sniping from the Win.GUI sniper).  Here's how it works:

1) We are still feeding our bots with data from our sniping server.  However, only pokemon within a small range will be processed and added to the sniping lists.  This range is configurable (see below).
2) There are 2 movement options for sniping: a) Teleporting, and b) Walking.  
3) Teleporting MAY result in catch flee when encountering the pokemon.  This seems to be dependent on how far the jump is. Teleporting may also not be that much faster - you may notice a long pause (up to 30 seconds) after the jump. This is due to the bot refreshing the map and waiting for the teleport softban to expire.
4) Walking is always reliable but obviously takes some time to walk to the target.  There are several options for walking: a) Catching other pokemon while walking, b) Spinning pokestops while walking, c) Speed up your walking speed (higher than your "normal" walking speed).

The settings that the auto sniper is checking:

"HumanWalkSnipeConfig": {
    "Enable": true,
    "MaxDistance": 1500.0,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
  },

If `HumanWalkSnipeConfig.Enable` is true, then we'll walk to the snipe target. Otherwise we do a teleport like before.  Note that yo may frequently get catch flee when catching pokemon after teleport due to Niantic's new serverside checks on distance.

`HumanWalkSnipeConfig.MaxDistance` will determine which pokemon show up for sniping. Only pokemon within this range will be snipable.

`HumanWalkSnipeConfig.CatchPokemonWhileWalking` will allow you to catch other pokemon while walking to your snipe target.

`HumanWalkSnipeConfig.SpinWhileWalking` will allow you to spin pokestops while walking to your snipe target.

`HumanWalkSnipeConfig.AllowSpeedUp` allows you to increase walking speed when moving to sniping target.

`HumanWalkSnipeConfig.MaxSpeedUpSpeed` is the max speed when using the `AllowSpeedUp` option.

In my limited experience testing the settings, a sniping configuration with a `MaxSpeedUpSpeed` of around 200 is working pretty well.  I'm curious to have people play with this and share what the best `MaxSpeedUpSpeed` speed is before the softban starts to slow things down.

### CODE REVIEW

**Comment by informer0827** [comment]
Can't wait for this release~~

**Comment by Instinct1** [comment]
is teleport sniping gone?

**Comment by CDAGaming** [comment]
Beta Tonight for it xD

**Comment by CDAGaming** [comment]
Nvm it's on v171

**Comment by jjskuld** [comment]
@Instinct1 v171 supports teleport sniping but it may or may not work reliably depending on the teleport distance.  You can give it a shot by setting `HumanWalkSnipeConfig. Enable` to `false`.

When I was testing local teleport sniping with pokemon with a sniping radius of 1000m, the pokemon would frequently catch flee.

**Comment by Instinct1** [comment]
:(

**Comment by Instinct1** [comment]
@jjskuld do you think long range teleport sniping without flee will ever be possible again?

**Comment by informer0827** [comment]
@jjskuld do you think Niantic will change location detection technique to old way and let you snipe on it?

**Comment by informer0827** [comment]
@Instinct1 do you think Niantic will change location detection technique to old way and let you snipe on it?

**Pull request merged**
