### PR TITLE
Enable multiple API Key in config

### PR DESCRIPTION
**Pull request by samuraitruong**
Allow using multiple Hash API Key
Do not make new connection to snipe server when reach limit

### CODE REVIEW

**Comment by jjskuld** [comment]
Regarding the multiple device ids, i was thinking of same thing for a while. The only difference in implementation is that there needs to be a salt used, otherwise it's easy for Nia to detect this if they were reading the implementation.

Also I would suggest that we just store it in auth.json alongside username password and have it serialized into the accounts.db.  You really want all of this information stored together ideally since the device id is dependent on the username and the salt.

**Comment by samuraitruong** [comment]
Actually, the first thing I want to do is make device ID in authconfig, but few min later I realize that none want to fill it when they have to config 20-200 account .  I will add random string and move the device.id key inside account folders.

**Comment by jjskuld** [comment]
The implementation of the salt is not correct because the salt needs to be stored with the device id, otherwise the device id is just random every time.

**Comment by jjskuld** [comment]
In other words, salt is only random generated the first time around, and from then on the same salt is used with the username to generate the device id.

**Pull request merged**
