### PR TITLE
Cert File For GUI Use

### PR DESCRIPTION
**Pull request by hardknoxni69a**
Adding The Cert File For GUI use If You think we should allow as most people should just use the WIN

### CODE REVIEW

**Comment by jjskuld** [comment]
I don't understand.. why for GUI use but the changes are all for the CLI?

**Comment by hardknoxni69a** [comment]
Without the cert file the websocket doesn't load so people can use electron
or whatever been getting messages about it the socket not loading without
it anymore I use the new WIN but some people are old-school using the
console and want to load gui seperate

**Comment by jjskuld** [comment]
It seems like cert.pfx is the one that needs to be copied.  

But it looks like references to PoGo.NecroBot.CLI_TemporaryKey.pfx got added to the project file even though it is not being used. Can you remove this from the csproj?

**Comment by hardknoxni69a** [comment]
Ya sure thing I thought that was the process before the file.got made I'll
remove that part though

**Comment by jjskuld** [comment]
Closing this in favor of #1262

**Pull request closed without merging**
