### PR TITLE
Adds Pause Functionality to NecroBot.WIN (NOT READY)

### PR DESCRIPTION
**Pull request by CDAGaming**
These Commits will Add Pause and Play Functionality to the Bot

Signed-off-by: CDAGaming <cstack2011@yahoo.com>

### CODE REVIEW

**Comment by jjskuld** [comment]
This is sort of a non-trivial task and requires a bit of thought to get right.

I think the best add this functionality is to add a new PauseState to the state machine in Logic.  You can follow the states around by look in the Logic.State package.  

The state machine is started in Program.cs and it enters the VersionCheckState() initially.  It then transitions into the next state:

VersionCheckState -> LoginState -> LoadSaveState -> CheckTosState -> InfoState -> FarmState

1) Step 1 is to add a new PauseState at the beginning of the chain.

PauseState -> VersionCheckState -> LoginState -> LoadSaveState -> CheckTosState -> InfoState -> FarmState

2) This is only half the problem though. We also want to be able to jump into PauseState from any of the other states.  And then we want to be able to jump back to where we left off after we leave PauseState.  In the bot whenever we want to switch to another state, we typically throw an exception (i.e. look at ActiveSwitchByRuleException).  So we could add a PauseStateException and hook up the UI button click to just throw the exception.  

3) Then we would have to go through the code and make sure that we are handling this exception properly by catching it and transitioning to PauseState when we catch the PauseStateException.  The PauseStateException constructor should have been passed the previous state so that if the bot clicks the button to resume execution, then it would switch back to the previous state.

**Comment by CDAGaming** [comment]
Wow Thanks @jjskuld. Originally, this method was going to be similar to Rocketbots Implement, which ultimately has some bugs. Will try your way of implementation once I am home

**Comment by Lord-Haji** [comment]
CDA actually iframe is invalid in markdown I was unaware

**Comment by CDAGaming** [comment]
Closing This Off for Now, will come back to this when i have time 👍

**Pull request closed without merging**
