### PR TITLE
Extended Integration of PokeEase & Win GUI + Build Fixes

### PR DESCRIPTION
**Pull request by CDAGaming**
## Description
- This Pull Request includes Integration for PokeEase for Win GUI, worked on also by @jjskuld .
- This PR also includes Updates to several Outdated dependencies and Fixes for Microsoft Rule Violations in event names, and other items.

## Projects Effected
- Necrobot.WIN
- Necrobot.CLI
- Necrobot.Logic

## Features
- Full Integration of DotNetBrowser w/ PokeEase (Needs Port Usage Bypass, and Full License)
- Updates to 9 Outdated Dependencies (Issues with Updating ChromeDriver)

## Bugs & In Progress Features
- PokeEase & Necrobot Needs Support to bypass Websocket, or auto use any open ports (In Progress)
- DotNetBrowser requires a full License for Production (In Progress)
- RocketAPI Dependency Version Mismatch (Seperate PR for them needed or their own update to deps)

## ETA Release Date:
- Late Q1 2017 - Early Q2 2017
- [Latest Build(Win GUI)](http://www.mypogosnipers.com:8080/job/nc/job/NecroBot/job/PR-1354/3/artifact/PoGo.Necrobot.Window/bin/Release/*zip*/Release.zip)

### CODE REVIEW

**Comment by jjskuld** [comment]
I'm still seeing references to ..\packages in the csproj files.  Can you please go through each of the 3 csproj files and just do a global search and replace for "..\packages" to "$(SolutionDir)\packages".

**Comment by CDAGaming** [comment]
Line 483 of PoGo.NecroBot.CLI.csproj seems to be the only last reference to ..\packages instead of $(SolutionDir)\packages, fixing now @jjskuld

**Comment by jjskuld** [comment]
PoGo.NecroBot.CLI.csproj line 195, 198, and 443 (at the end of the line) still has references to ..\packages

**Comment by jjskuld** [comment]
PoGo.NecroBot.Logic.csproj has references to ..\packages on line 94, 120, 127, 130, etc.. (a whole bunch more)

**Comment by jjskuld** [comment]
PoGo.Necrobot.Window/PoGo.Necrobot.Window.csproj same on line 592 and 636

**Comment by CDAGaming** [comment]
:/ Ok, Will be fixed in a bit @jjskuld , Thanks for letting me know

**Comment by CDAGaming** [comment]
@jjskuld Did a Full Search so there should not be anymore ../packages references

**Comment by CDAGaming** [comment]
Jenkins Build Failed as it timed out, but it will be successful. Might have to make a dummy commit to ensure it succeeds to later...

**Comment by samuraitruong** [comment]
hey, who will sponsor for the license?

**Comment by CDAGaming** [comment]
@jjskuld had said he would be getting a license for the browser, as far as i know of rigtht now @samuraitruong

**Comment by jjskuld** [comment]
Before I merge this, I want to discuss with everyone which direction we want to take? Multiple GUI projects or just a single one with PokeEase integration?

**Comment by CDAGaming** [comment]
@jjskuld Why not let the users decide that, we can ask in announcements like a poll to see what they'd like to go for :D

**Comment by CDAGaming** [comment]
Or We may Add a config option to Enable or Disable the Browser as well

**Comment by CDAGaming** [comment]
@jjskuld SuperBuild will be replacing this PR for Master tomorrow, but it'll have a LOT more changes to it

**Comment by joe1chen** [comment]
@CDAGaming Can you split up this PR into several PR's by using feature branches?  I'd like to merge in your changes to fix the naming of the handlers and the updates to the packages, but hold off on the DotNetBrowser merge into master.  If you have other changes targeting the DotNetBrowser branch, you can open a pull into that branch.

**Comment by CDAGaming** [comment]
DotNetBrowser can be removed and added again in a seperate PR into features/DotNetBrowser while the other 3 PR(FeroxRev,master, PoGoProtos) will still be submitted in their appropriate master branch

**Pull request merged**
