### PR TITLE
Gym update

### PR DESCRIPTION
**Pull request by ziomber**
Added function to prioritize gyms with free slots to go there first

### CODE REVIEW

**Comment by samuraitruong** [comment]
now I know why we have API call throttle with Fortdetails, since you call this function everytime 

Look at CanDeployGyms
 var task = session.Client.Fort.GetGymDetails(fort.Id, fort.Latitude, fort.Longitude);

IT execute this API call, if you have 10 GYM in range then make 10 API call everytime. that will make bot run slow got lot of FortDetails api call failed

**Comment by ziomber** [comment]
Ok, what do you suggest? Cache them?

**Comment by samuraitruong** [comment]
get map object will execute every 10 sec, I suggest not check fort state frequence, just do check every 10 min . also the api UpdatePlayer has change, maysure you update gym function to work with hat change

**Comment by ziomber** [comment]
Still i heve **can't start battle** messages quite often (see #820). There are not so many as before update but still they are.
I can't reproduce { "result": "ERROR_INVALID_ATTACK_ACTIONS" } error.

**Comment by ziomber** [comment]
@samuraitruong i'm almost 100% sure that our latest problems are related with swap pokemon function.
99% of  **can't start battle**'s are after call to this API call where BattleAction.Type is BattleActionType.ActionSwapPokemon. 
When i disable this swaping and with this update prioritizing free slot gyms takeing 10 gyms in my town  takes much less time than before.

**Comment by ziomber** [comment]
This is strange for me becouse swaping is workig and don't produce any errors.

**Comment by samuraitruong** [comment]
I merge in, We improve it day by day

**Comment by nhumber** [comment]
player switch is working great for me. i ran this all night and bot was still working at it should this AM.
only thing i still really want to see is a MAX CP TO USE WHILE TRAINING, the bot doesnt make it through full lineups.. it makes no sense to level up a gym at 100points per battle when we could be getting 500-1000 by just choosing the right CP level.. all 6 attackers must be below cp of first defender, unless first defender is below 1000cp, in that case defender level should be calculated with second defender.

**Comment by redking974** [comment]
@ziomber do you know if during a battle Necrobot could switch Pokemon before they die (trying to switch if Pokemon have less HP than XXX) or we must to leave them die ?
It could be practice to save revive (less frequent than potions I believe)

**Pull request merged**
