### PR TITLE
Features/accounts management

### PR DESCRIPTION
**Pull request by Lord-Haji**
### DO NOT MERGE
Closes at #762

### CODE REVIEW

**Comment by Lord-Haji** [comment]
@jjskuld

**Comment by jjskuld** [comment]
@Lord-Haji I'd like to rework this into a slightly different form.  Instead of putting the add account form into the accounts page, we should add a "Add Account" button which opens a popup dialog.

**Comment by jjskuld** [comment]
I'm going to close this PR but leave the `features/AccountsManagement` branch around for reference.

**Comment by Lord-Haji** [comment]
Ok :3

**Pull request closed without merging**
