### PR TITLE
SuperBuild PR - Necrobot (WIP, Submodule PRs Required)

### PR DESCRIPTION
**Pull request by CDAGaming**
## Features
- All Dependencies Updated to Latest (No Issues @jjskuld, according to several tests)
- Many Typos have been Fixed
- Many Optimizations/Simplified Code-Behind for a Faster Expierience
- Support for iOS Devices Up to 10.3
- License is now Properly an Embedded Resource so it is not visible
- Adds More Extended PokeEase Integration
- Fixes GUI Settings Descriptions (Empty or with typos, WIP)

## Known Bugs
- Sometimes, Going on the Hub/Browser Tab, the DotNetBrowser would take up the full screen
Workaround: Resize the screen a little bit for it to correct itself

## Requirements
- If you are Testing/Building this Source, Please don't forget to Get the other Pull Requests for the Submodules (FeroxRev, PoGoProtos)

## Downloads
Build 0401 - Coming Tomorrow
Build 0330 - [Click Here](https://mega.nz/#!3MhETZrK!m_H0g9QD7X9HgTxfJtLHR049kJfSELaZGTIr95nn88Q)

### CODE REVIEW

**Comment by CDAGaming** [comment]
Oddly, This Builds fully in VS2017 with all the other PRs, just not in Appveyor...Weird

**Comment by jjskuld** [comment]
Can you try in VS2015?  I believe Appveyor is running 2015, not 2017.

**Comment by jjskuld** [comment]
When I get some time, I'll pull down your master from your fork and see if i can figure out what's going on.

**Comment by CDAGaming** [comment]
PR and repos are going to be Reuploaded as something screwed up

**Comment by jjskuld** [comment]
@CDAGaming By the way thanks for all the little cleanup. I like the attention to detail, like fixing the capitalization on method names to follow MSFT best practices.  Looking forward to a clean pull.

**Pull request closed without merging**
