### PR TITLE
Bug Fix: Pokemon Count Display

### PR DESCRIPTION
**Pull request by Lord-Haji**
The Pokemon Count Display was getting stuck at 241/250 when full.
This Might Fix

I haven't tested

### CODE REVIEW

**Comment by jjskuld** [comment]
It's the wrong fix since the count is the number of pokemon.  So instead of 250 being card-coded, it should be dynamic to the number of inventory spaces left.

**Comment by jjskuld** [comment]
Re-opening so we can fix the max from hard-coded 250 to a true inventory left.

**Comment by Lord-Haji** [comment]
@jjskuld thats different issue.
I actually fixed the bug which always displayed 241 when the Pokemon Box is full

**Comment by jjskuld** [comment]
I see eggs count against pokemon inventory.  So the correct fix is to subtract eggs count from 250.  It should say 241/241 when fixed since the tab only counts pokemon.

**Comment by Lord-Haji** [comment]
@jjskuld thats kinda right. But people may get confused as the people see the number of Pokemon in terms of 250/250 in the Pokemon GO App

**Comment by hardknoxni69a** [comment]
Ya it should show 250/250 if you have 9 eggs most people know that the eggs count as pokemon. But it should be Pokemon count plus egg / total size of users bag fix 2 birds with one stone because bag size just shows default it doesn't actually pull the bag size value from server

**Comment by jjskuld** [comment]
Ok, let's go with this change for now. I think 241/241 may be confusing.

**Pull request merged**
