### PR TITLE
fix default snipe links

### PR DESCRIPTION
**Pull request by Furtif**
## Fix snipe defaults

### CODE REVIEW

**Comment by hardknoxni69a** [comment]
pretty sure this is supposed to stay as necrosocket as its the main link then it gets uploaded to mypogo

**Comment by Furtif** [comment]
this works fine

**Comment by Lord-Haji** [comment]
@hardknoxni69a I think the same

**Comment by CDAGaming** [comment]
Merged with HydraBuild :)

**Comment by Furtif** [comment]
Look this @hardknoxni69a https://github.com/Necrobot-Private/NecroBot/issues/1543

**Comment by hardknoxni69a** [comment]
i know it works but i dont think mypogo accepts the data feedback so once people switch over the results will no longer display
necrosocket is the main server that processes the incoming feeds from bots and uploads to mypogo and vip server if we start sending data to mypogo it wont get processed correctly as its not made receive coords  pretty sure i would imagine truong would have set mypogo if that was meant to be all i know since people are switch over results have already been cut drastically

**Pull request merged**
