### PR TITLE
Updates TinyIoC.cs

### PR DESCRIPTION
**Pull request by CDAGaming**
This PR Realigns TinyIoC.cs to Master and Includes several Bug-Fix PR Changes:

Included PRs:
https://github.com/grumpydev/TinyIoC/pull/114
https://github.com/grumpydev/TinyIoC/pull/111
https://github.com/grumpydev/TinyIoC/pull/110
https://github.com/grumpydev/TinyIoC/pull/105

### CODE REVIEW

**Comment by Lord-Haji** [comment]
@CDAGaming why r u merging unmerged PRs, if they get rejected we shall have trouble too

**Comment by CDAGaming** [comment]
@Lord-Haji These PRs were common changes in the other Prs. They were bug-fixes for TinyIoC that the origin dev hadn't merged, maybe because of lack of time or dropping of project. If you read what the PRs do, they do not seem to have any controversy as other prs on there have had

**Comment by jjskuld** [comment]
Makes me wonder if we should be using a better IoC solution, one that is supported.

Take a look at http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison

**Comment by jjskuld** [comment]
Based on the above link, DryIoc looks pretty good and is constantly being updated. 

https://www.nuget.org/packages/DryIoc/

Just updated a few days ago.

**Comment by CDAGaming** [comment]
@jjskuld Hm, looks good, May test this out in a bit :)

Would be better than TinyIoC, as it seems origin dev is MIA is seems

**Pull request merged**
