### PR TITLE
Some translation + polish translation

### PR DESCRIPTION
**Pull request by SLASHLogin**
Don't merge please. 
tasks bar sentences "pokemons {0/1}" and "items {0/1}" are still in English and some things still need it's place in translation. I might do that but I don't know which files I have to change to work good.
Where appears "close"?

### CODE REVIEW

**Comment by SLASHLogin** [comment]
There's bug. When launching WIN "show console" is translated but when click it shows only in english and the same with second click.

**Comment by samuraitruong** [comment]
ah, I saw that, this console text in the code 👍  I will fix it soon

**Comment by samuraitruong** [comment]
are u happy to merge?

**Comment by samuraitruong** [comment]
#fix that console issue in #882

**Comment by samuraitruong** [comment]
U will busy now, just make setting form work with translation, now you have to translate 600 lines more

**Pull request merged**
