### PR TITLE
Gym Battles updates

### PR DESCRIPTION
**Pull request by ziomber**
## Short Description:
almost nothing more than previous pull request

### CODE REVIEW

**Comment by samuraitruong** [comment]
Thanks for improving that, keep update this until I finish GUI then we will merge and test,

**Comment by sammy150681** [comment]
My bot dont fight against others gym

**Comment by ziomber** [comment]
it's not merged yet, so you don't have my changes probable

**Comment by ziomber** [comment]
can you merge my fork? i have to old files :(

**Comment by sammy150681** [comment]
Your bot dont fight against enemie gym?

**Comment by ziomber** [comment]
sammy, i'm totally new at github so i can't explain you. I've fixed all gym battle module and made a pull request with means that samuraitruong who is the owner of original version can see it and decides when he will merge and make them public. As for now master branch doesn't contain my code but as soon as it will be possible samuraitruong will merge files and you will be able to check it :)

**Comment by ziomber** [comment]
Shit, don't bother with test, i've found another bug :(

**Comment by samuraitruong** [comment]
the release yesterday hasn't been merge @ziomber , lets me know when you fix the new bug and I will merge and test then release,

**Comment by ziomber** [comment]
you can merge it and check on bigger gyms 4+ defenders

**Comment by samuraitruong** [comment]
ok, I will merge tonight

**Pull request merged**
