### PR TITLE
Win GUI Reworked Layout - Bottom Tabs - Request for Feedback

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
This is a re-layout of the tabs to the bottom of the window. I think it makes it a little cleaner.  On some of my low resolution screens also the vertical tabs would cut off the last tab (eggs), so this is a bit better for low resolution screens.

screen shot 2017-05-05 at 8 29 59 pm

### CODE REVIEW

**Comment by CDAGaming** [comment]
Nice 👍

**Comment by jjskuld** [comment]
I was only able to fix dotnetbrowser layout by switching to lightweight mode. For now I think lightweight mode is good enough. 

Heavyweight mode renders funny and I'm not sure how to fix. Will probably need to open a support request.

**Comment by jjskuld** [comment]
I guess if people have strong opinions about the button location we could also make it a configurable option. So they can move back to left aligned buttons.

**Comment by CDAGaming** [comment]
@jjskuld That Browser issue can be fixed with DPI-Awareness, which is what i was planning to implement for .net 4.7, as it supports it much more

**Comment by CDAGaming** [comment]
https://dotnetbrowser.support.teamdev.com/support/solutions/articles/9000110315-winforms-heavyweight-rendering-and-dpi-awareness

Could possibly apply this to WIN, just in a different compatible way

**Pull request merged**
