### PR TITLE
Fix #179 WildPokemon-error with Incense/Lures

### LINKED ISSUE #179: 0.9.9.6 'POGOProtos.Networking.Responses.DiskEncounterResponse' does not contain a definition for 'WildPokemon'
Version: 0.9.9.6
Windows Version: 10
necerror 3

What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

### PR DESCRIPTION
**Pull request by mo0ojava**
Fixes the problems with WildPokemon etc not working with Incense/Lures.

Ugly/untidy version. In a hurry so will have to clean up the code later. Seemingly works though. Second opinion welcome!

### CODE REVIEW

**Comment by mo0ojava** [comment]
Hm. The changes to MSnipeService aren't solid.  Have to verify the response type there as well.

**Comment by mo0ojava** [comment]
Should work as this as long as MSnipe never runs into any other responses than Wildpokemon

**Comment by iwean** [comment]
Maybe you can talk it to @msx752, so it will no conflict at the server...

**Comment by msx752** [comment]
My fault. İ am on way, now i cant Access to computer . Thanks

**Comment by mo0ojava** [comment]
Went through that part again and I don't thing it should intervene with msx's code. It appears MSnipe only accepts EncounterResponse to begin with so it was never an issue.

**Pull request merged**
