### PR TITLE
Features/improve auto update

### PR DESCRIPTION
**Pull request by Lord-Haji**
### Short Desc
This will show up the description from the CHANGELOG.md as nowadays we don't uploaded the rtfs

P.S : We need to set up GitHub Changelog generator or add them manually

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Build will fail cause its still incomplete will get it to work ASAP

**Comment by CDAGaming** [comment]
Testing this in a moment, as I just got up

**Comment by CDAGaming** [comment]
At this time, it seems it's only this error(Full Log):
`
System.Net.WebException occurred
  HResult=0x80131509
  Message=The server committed a protocol violation. Section=ResponseStatusLine
  Source=System
  StackTrace:
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at PoGo.NecroBot.Logic.Forms.AutoUpdateForm.AutoUpdateForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by CDAGaming** [comment]
@Lord-Haji You going to fix those build conflicts? If your concerned on changed DM me the diffs it's picking up and I'll choose which ond

**Pull request merged**
